### ISSUE TITLE
Add sub-commands

### ISSUE THREAD

**Issue by nloveladyallen** [youtux/homebrew-livecheck#8]
With Homebrew, you can run `brew edit formula` and you editor will open the formula, or `brew cat formula` to display the formula, etc. I suggest adding `brew livecheck edit livecheckable`, `brew livecheck cat livecheckable`, etc. to allow easier editing of livecheckables. There are no formulae (at least in core) conflicting with these commands, so `brew livecheck cat livecheckable` would not be ambiguous between displaying the livecheckable and livechecking the livecheckables `cat` and `livecheckable`.

**Comment by youtux** [comment]
I think this is a great idea! If you want to make a PR I will definitely review and merge it, otherwise I'm not sure if I'll have the time to implement it.

**Comment by youtux** [comment]
Fixed by #9
